[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile --prod=false"]

[phases.build]
cmds = ["NODE_OPTIONS='--max-old-space-size=512' pnpm build"]

[start]
cmd = "NODE_OPTIONS='--max-old-space-size=512' pnpm start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=512"

